name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt10
        with:
          flow: openlane2

      # Debugging: List all files to find the correct Yosys log location
      - name: Debug - List all files
        if: always()
        run: find . -type f | tee file_list.txt

      # Debugging: Find where yosys.log is actually located
      - name: Find Yosys Log
        if: always()
        run: find . -name "yosys.log" || echo "yosys.log not found"

      # Save Yosys logs if they exist
      - name: Save Yosys Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yosys-logs
          path: "**/yosys.log"
          if-no-files-found: warn  # Prevents failure if log is missing

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@tt10

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@tt10

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt10
